version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: ./server
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
  client:
    build: ./client
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api

    