version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    # ports:
    #   - 5432:5432 
  api:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db

    